### ISSUE TITLE
Citations 

### ISSUE THREAD

**Issue by momipsl** [ES-DOC/esdoc-cim#16]
A citation is currently defined somewhat awkwardly:

[shared.reference](https://github.com/ES-DOC/esdoc-cim/blob/master/v2/schema/shared_classes.py#L279-293)
[shared.citation_target](https://github.com/ES-DOC/esdoc-cim/blob/master/v2/schema/shared_classes.py#L29-53)

It could be simplified by collapsing the 2 classes into one as it was originally.

**Comment by bnlawrence** [comment]
The reason they are separate is that the first is a class aimed at being embedded in a parent document, which is effectively an association class to the second, which is a standalone document. This allows different references (reasons for citing the) to one citation target document.

**Comment by momipsl** [comment]
shared.DocReference class should be sufficient ... there seems to be no need to introduce shared.reference.

**Comment by momipsl** [comment]
Have simplified by introducing a single new class: shared.Citation.  References to a concrete instance will be made using an instance of the shared.DocReference class.
