### ISSUE TITLE
other_names identifier for experiments

### ISSUE THREAD

**Issue by charliepascoe** [ES-DOC/esdoc-cim#18]
Many of the CMIP6 experiments are known by more than one name, there's the name that the MIP teams used, the name in the data request, and the name that Karl Taylor has created for the drs.
The CIM2 experiment documents have three kinds of name:
name (I've used the convention MIPNAME#.#)
long_name (to be the same as Karl's experiment title)
canonical_name  (same as Karl's experiment_id)

I would like to propose an additional identifier: other_names
The other_names parameter would have a zero to many multiplicity and would be used to record the names that experiments have also been known as.
I'll add them to my spreadsheets as a comma separated list.

**Comment by murphysj** [comment]
God forbid have just one name!

On Fri, May 13, 2016 at 4:02 AM, Charlotte <notifications@github.com> wrote:

> Many of the CMIP6 experiments are known by more than one name, there's the
> name that the MIP teams used, the name in the data request, and the name
> that Karl Taylor has created for the drs.
> The CIM2 experiment documents have three kinds of name:
> name (I've used the convention MIPNAME#.#)
> long_name (to be the same as Karl's experiment title)
> canonical_name (same as Karl's experiment_id)
>
> I would like to propose an additional identifier: other_names
> The other_names parameter would have a zero to many multiplicity and would
> be used to record the names that experiments have also been known as.
> I'll add them to my spreadsheets as a comma separated list.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ES-DOC/esdoc-cim/issues/18>
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by momipsl** [comment]
Have added an alternative-names attribute to handle this use case.  The underlying Activity class now has the following name related attributes:

canonical_name, internal_name, long_name, name & alternative_names.
